### ISSUE TITLE
java.io.IOException after scanning initialization code

### ISSUE THREAD

**Issue by schroupienl** [pretix/pretixscan-android#20]
Hello folks.

I am playing around with a pretix 3.9.0 running in a docker container behind an apache2 ssl proxy.

I've tried the pretixscan iOS App which is working fine.

When I try to connect a new Windows (or Android) device, the App crashes with

java.io.IOException
	at eu.pretix.libpretixsync.setup.EventManager.parseEvents(EventManager.kt:85)
	at eu.pretix.libpretixsync.setup.EventManager.parseEvents$default(EventManager.kt:41)
	at eu.pretix.libpretixsync.setup.EventManager.getAvailableEvents(EventManager.kt:34)
	at eu.pretix.pretixscan.desktop.ui.SelectEventController.fetchEvents(SelectEventController.kt:16)
	at eu.pretix.pretixscan.desktop.ui.SelectEventView$loadEvents$1.invoke(SelectEventView.kt:203)
	at eu.pretix.pretixscan.desktop.ui.SelectEventView$loadEvents$1.invoke(SelectEventView.kt:25)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by raphaelm** [comment]
Pretty sure this is in the wrong repository, and likely outdated anyways
